dist: bionic

services:
- docker

before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- cp env.template .env
- cp develop.yml docker-compose.yml

env:
  matrix:
  - DOCKER_COMPOSE_VERSION=1.25.4
  global:
    secure: XlEaYW7Ywou33lvC+zhBAaQEp7dzu3bpHi3xp7FCus4MnSD49neltY/z6iIAH2/ETju5XW5SlNj7m03STMuCJ1QwNujSlXfJ6USalF75Vd9eO8sKQiUGS8eoRD4C4uN1thwxaHsuD/Xeup8C1PeCV8j9eh8cD1KQfyN+DBYgJETAmP3Lvgl6YMrJO7GtLuZ/jz8iVAe/heNvissy5Px/0tcFHQShcbW79dKXsUs4oV5GtQDFj+ygF7BysZwy3BQTuRprLIeQos1Wf4N+AZUnrvSJpMgR3FGK8Cuc8VWhp1KoWC5xPbyM2hO9mYnawv7a5LE6XQwwBVAB13MBlpGl17sL4nmo6eX2uSxCb4nlfdRDeeDcDRLL+sYBzAi7IEwzpiOtKqStNnHlauIvzUMJPB9UKI2Asinp8lAY68gVfpL7kqnowWH9clZQ8Irh3MwJrZEEGgyYzYHtDS+58/pRk8Fs3UnKI2P17k3PNfo6Qf6z/5LPnto09P1Vqlgn35re2qBkHgXsCsVzps72pFbMuOa7F15azRrs5A4ZH4dfRsnllsXoBa2zPwS0n2cF14+TLa/ipz663YPJ4cj1xqNQnHkR7i4FiSRscFB0HAozAg47n2auW3QRvI6goQAD3gjY5Vpb+ibT/dD7zUN5jgZIghzxGqSMm5E3pRjV6aP4YcU=

jobs:
  include:
  - stage: build docker image
    if: type = pull_request
    script:
    - "/usr/local/bin/docker-compose build"
  - stage: deploy docker image
    if: type != pull_request and branch = 'master'
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - "/usr/local/bin/docker-compose build"
    - docker push geekbeacon/nixie_www:latest
