version: '3.7'
services:
  nix_www:
    image: geekbeacon/nixie_www:latest
    build:
        context: . 
        dockerfile: docker/app/Dockerfile
    env_file: .env
    volumes:
        - ./resources:/app/resources
        - ./public:/app/public
    restart: always
    ports:
      - "9001:9000"
  nix_db:
    image: mysql:5.7.29
    restart: always
    env_file: .env
    volumes:
        - ./data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT 1 + 1" --skip-column-names -B']
      interval: 10s
      timeout: 5s
      retries: 5
