version: '3.7'
services:
  nix_www:
    image: geekbeacon/nixie_www:latest
    env_file: .env
    restart: always
    ports:
      - "9001:9000"
    networks:
       - shared_backend
    external_links:
      - shared_mysql

networks:
    shared_backend:
        name: shared_backend
        external: true
